TOP=..

include $(TOP)/configure/CONFIG
#----------------------------------------
#  ADD MACRO DEFINITIONS AFTER THIS LINE


PROD_HOST += putNoBlock
putNoBlock_SRCS += putNoBlock.cpp
putNoBlock_LIBS += pvaClient pvAccess pvData ca Com

#===========================

include $(TOP)/configure/RULES
#----------------------------------------
#  ADD RULES AFTER THIS LINE

